apiVersion: apps/v1                 # Correct API version
kind: StatefulSet                  # Resource type

metadata:
  name: mysql-statefulset           # Name of StatefulSet
  namespace: mysql                  # Namespace

spec:
  serviceName: mysql-service       # REQUIRED for StatefulSet
  replicas: 3                       # Number of MySQL pods

  selector:
    matchLabels:                    # ❌ was matchLables
      app: mysql

  template:                         # ❌ was templates
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306

        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-config-map
              key: MYSQL_DATABASE 
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql  # MySQL data directory

  volumeClaimTemplates:             # ❌ indentation was wrong
  - metadata:
      name: mysql-data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:                   # ❌ was request
          storage: 1Gi

